listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        file;
srs_log_level       warn;
srs_log_file        ./objs/srs.log;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         off;
    listen          8080;
    dir             ./objs/nginx/html;
}

srt_server {
    enabled         on;
    listen          10080;
}

vhost __defaultVhost__ {
    srt {
        enabled     on;
        srt_to_rtmp on;
    }

    http_hooks {
        enabled     on;
        on_publish  http://localhost:8080/api/srs/on_publish;
    }
}
