listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

vhost __defaultVhost__ {
    ingest srt {
        enabled     on;
        input {
            type    stream;
            url     srt://0.0.0.0:10080?mode=listener;
        }
        ffmpeg      /usr/local/srs/objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled on;
            vcodec  copy;
            acodec  copy;
            output  rtmp://127.0.0.1/live/stream;
        }
    }

    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    2;
        hls_window      10;
    }
}
